/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatComponent: typeof import('./src/components/chat/ChatComponent.vue')['default']
    copy: typeof import('./src/components/micro-frontend/MicroAppContainer copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    HistoryChatSidebar: typeof import('./src/components/chat/HistoryChatSidebar.vue')['default']
    InputArea: typeof import('./src/components/chat/InputArea.vue')['default']
    MarkdownRenderer: typeof import('./src/components/markdown/MarkdownRenderer.vue')['default']
    MessageItem: typeof import('./src/components/chat/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/chat/MessageList.vue')['default']
    MicroAppContainer: typeof import('./src/components/micro-frontend/MicroAppContainer.vue')['default']
    'MicroAppContainer copy': typeof import('./src/components/micro-frontend/MicroAppContainer copy.vue')['default']
    MyCollapse: typeof import('./src/components/collapse/MyCollapse.vue')['default']
    MyDropdown: typeof import('./src/components/dropdown/MyDropdown.vue')['default']
    MySelect: typeof import('./src/components/select/MySelect.vue')['default']
    MySubsection: typeof import('./src/components/subsection/MySubsection.vue')['default']
    MySwiper: typeof import('./src/components/swiper/MySwiper.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SidebarItem: typeof import('./src/components/chat/SidebarItem.vue')['default']
    SidebarMenuItem: typeof import('./src/components/layout/SidebarMenuItem.vue')['default']
    SvgIcon: typeof import('./src/components/icons/SvgIcon.vue')['default']
    VerticalMenu: typeof import('./src/components/layout/VerticalMenu.vue')['default']
  }
}
